apiVersion: compute.mycloud.com/v1
kind: EC2Instance
metadata:
  labels:
    app.kubernetes.io/name: ec2-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
spec:
  # TODO(user): Add fields here
